In [1]:
import cv2
import numpy as np

In [2]:
photo =cv2.imread('lady.jpg')
cv2.imshow('hi', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [3]:
#DOWNLOAD THIS PRECREATED LIBRARY FOR DETECTING COORDINATES
model = cv2.CascadeClassifier('haarcascade_frontalface.xml')

In [4]:
faces = model.detectMultiScale(photo)
x1 = faces[0][0]
y1 = faces[0][1]
x2 = x1 + faces[0][2]
y2 = y1 + faces[0][3]
print(faces)
print(f" {x1}, {x2}, {y1}, {y2}")         #FORMAT FUNCTION
face_lady = cv2.rectangle(photo, (x1,y1) , (x2,y2), [255,255,255], 2)      #DRAW THE RECTANGLE
cv2.imshow("image", face_lady)
cv2.waitKey()
cv2.destroyAllWindows()

[[673 688  52  52]
 [335 214 151 151]]
 673, 725, 688, 740


In [ ]:
len(faces)

In [5]:
photo1 =cv2.imread('Harrypotter.jpg')
cv2.imshow('hi', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
faces1 = model.detectMultiScale(photo1)
x1 = faces1[0][0]
y1 = faces1[0][1]
x2 = x1 + faces1[0][2]
y2 = y1 + faces1[0][3]
print(faces1)
print(f" {x1}, {x2}, {y1}, {y2}")


[[101  72 188 188]]
 101, 289, 72, 260


In [7]:
face_harry = cv2.rectangle(photo1, (x1,y1) , (x2,y2), [255,255,255], 2)
cv2.imshow("image", face_harry)
cv2.waitKey()
cv2.destroyAllWindows()

# SWAPPING THE IMAGE

In [8]:
swap = photo[214:402, 335:523]
face_harry[72:260, 100:288] = swap
cv2.imshow("Swapped image", face_harry)
cv2.waitKey()
cv2.destroyAllWindows()